CREATE TABLE cliente (
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nome VARCHAR(50),
  endereco VARCHAR(50),
  bairro  VARCHAR(50),
 cpf VARCHAR(50),
 status  Integer,
 telefone VARCHAR(50),
 dataCadastro  date,
 dataNascimento  date,
 cidade_estado integer,
observacao varchar(50)

);


CREATE TABLE venda (
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  pedido integer,
  cliente Integer,
  parcelas Integer,
  valor  DECIMAL(50),
  data  date,

);

CREATE TABLE parcela (
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  alias varchar(50),
  venda Integer,
  valor  DECIMAL(50),
  vencimento  date,
  status integer,  


);

CREATE TABLE cidade_estado (
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  cidade varchar(50),
  estado varchar(50),

);
